import type { ThemeConfig, ResolvedTheme, ThemeColor, ThemeDefs } from './types.js'

// Built-in themes - OpenCode-inspired design system
export const themes: Record<string, ThemeConfig> = {
  opencode: {
    name: 'OpenCode',
    defs: {
      // Grayscale ramp (near-black to light)
      step1: '#0a0a0a',
      step2: '#111111',
      step3: '#1a1a1a',
      step4: '#242424',
      step5: '#2e2e2e',
      step6: '#3a3a3a',
      step7: '#484848',
      step8: '#606060',
      step9: '#808080',
      step10: '#a0a0a0',
      step11: '#c0c0c0',
      step12: '#eeeeee',
      // Accent colors
      orange: '#fab283',
      peach: '#f5a97f',
      blue: '#7dc4e4',
      purple: '#c6a0f6',
      green: '#a6da95',
      red: '#ed8796',
      yellow: '#eed49f',
      teal: '#8bd5ca',
      pink: '#f5bde6',
    },
    theme: {
      primary: 'orange',
      secondary: 'step10',
      accent: 'orange',
      error: 'red',
      warning: 'yellow',
      success: 'green',
      info: 'blue',
      text: 'step12',
      textMuted: 'step9',
      background: 'step1',
      backgroundPanel: 'step2',
      backgroundElement: 'step3',
      backgroundInput: 'step3',
      backgroundUser: 'step2',
      backgroundAssistant: 'step1',
      border: 'step5',
      borderActive: 'step7',
      borderSubtle: 'step4',
      selectedListItemText: 'step1',
      syntaxComment: 'step8',
      syntaxKeyword: 'purple',
      syntaxFunction: 'blue',
      syntaxString: 'green',
      syntaxNumber: 'orange',
      syntaxVariable: 'teal',
      syntaxOperator: 'step10',
      syntaxPunctuation: 'step9',
      syntaxType: 'yellow',
    },
  },
  catppuccin: {
    name: 'Catppuccin',
    defs: {
      base: '#1e1e2e',
      mantle: '#181825',
      crust: '#11111b',
      surface0: '#313244',
      surface1: '#45475a',
      surface2: '#585b70',
      overlay0: '#6c7086',
      overlay1: '#7f849c',
      text: '#cdd6f4',
      subtext0: '#a6adc8',
      subtext1: '#bac2de',
      lavender: '#b4befe',
      blue: '#89b4fa',
      sapphire: '#74c7ec',
      sky: '#89dceb',
      teal: '#94e2d5',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      peach: '#fab387',
      maroon: '#eba0ac',
      red: '#f38ba8',
      mauve: '#cba6f7',
      pink: '#f5c2e7',
      flamingo: '#f2cdcd',
      rosewater: '#f5e0dc',
    },
    theme: {
      primary: 'peach',
      secondary: 'mauve',
      accent: 'peach',
      error: 'red',
      warning: 'yellow',
      success: 'green',
      info: 'sapphire',
      text: 'text',
      textMuted: 'overlay1',
      background: 'crust',
      backgroundPanel: 'mantle',
      backgroundElement: 'base',
      backgroundInput: 'surface0',
      backgroundUser: 'mantle',
      backgroundAssistant: 'crust',
      border: 'surface1',
      borderActive: 'surface2',
      borderSubtle: 'surface0',
      selectedListItemText: 'crust',
      syntaxComment: 'overlay0',
      syntaxKeyword: 'mauve',
      syntaxFunction: 'blue',
      syntaxString: 'green',
      syntaxNumber: 'peach',
      syntaxVariable: 'teal',
      syntaxOperator: 'sky',
      syntaxPunctuation: 'overlay1',
      syntaxType: 'yellow',
    },
  },
  tokyonight: {
    name: 'Tokyo Night',
    defs: {
      bg: '#1a1b26',
      bgDark: '#16161e',
      bgHighlight: '#292e42',
      terminal: '#414868',
      fg: '#c0caf5',
      fgDark: '#a9b1d6',
      fgGutter: '#3b4261',
      dark3: '#545c7e',
      comment: '#565f89',
      dark5: '#737aa2',
      blue0: '#3d59a1',
      blue: '#7aa2f7',
      cyan: '#7dcfff',
      blue1: '#2ac3de',
      blue2: '#0db9d7',
      blue5: '#89ddff',
      blue6: '#b4f9f8',
      blue7: '#394b70',
      magenta: '#bb9af7',
      magenta2: '#ff007c',
      purple: '#9d7cd8',
      orange: '#ff9e64',
      yellow: '#e0af68',
      green: '#9ece6a',
      green1: '#73daca',
      green2: '#41a6b5',
      teal: '#1abc9c',
      red: '#f7768e',
      red1: '#db4b4b',
    },
    theme: {
      primary: 'orange',
      secondary: 'magenta',
      accent: 'orange',
      error: 'red',
      warning: 'yellow',
      success: 'green',
      info: 'cyan',
      text: 'fg',
      textMuted: 'comment',
      background: 'bgDark',
      backgroundPanel: 'bg',
      backgroundElement: 'bgHighlight',
      backgroundInput: 'bgHighlight',
      backgroundUser: 'bg',
      backgroundAssistant: 'bgDark',
      border: 'terminal',
      borderActive: 'dark3',
      borderSubtle: 'fgGutter',
      selectedListItemText: 'bgDark',
      syntaxComment: 'comment',
      syntaxKeyword: 'magenta',
      syntaxFunction: 'blue',
      syntaxString: 'green',
      syntaxNumber: 'orange',
      syntaxVariable: 'cyan',
      syntaxOperator: 'blue5',
      syntaxPunctuation: 'dark5',
      syntaxType: 'blue1',
    },
  },
  gruvbox: {
    name: 'Gruvbox',
    defs: {
      bg0Hard: '#1d2021',
      bg0: '#282828',
      bg1: '#3c3836',
      bg2: '#504945',
      bg3: '#665c54',
      bg4: '#7c6f64',
      fg0: '#fbf1c7',
      fg1: '#ebdbb2',
      fg2: '#d5c4a1',
      fg3: '#bdae93',
      fg4: '#a89984',
      red: '#fb4934',
      green: '#b8bb26',
      yellow: '#fabd2f',
      blue: '#83a598',
      purple: '#d3869b',
      aqua: '#8ec07c',
      orange: '#fe8019',
      gray: '#928374',
    },
    theme: {
      primary: 'orange',
      secondary: 'purple',
      accent: 'orange',
      error: 'red',
      warning: 'yellow',
      success: 'green',
      info: 'blue',
      text: 'fg1',
      textMuted: 'gray',
      background: 'bg0Hard',
      backgroundPanel: 'bg0',
      backgroundElement: 'bg1',
      backgroundInput: 'bg1',
      backgroundUser: 'bg0',
      backgroundAssistant: 'bg0Hard',
      border: 'bg2',
      borderActive: 'bg3',
      borderSubtle: 'bg1',
      selectedListItemText: 'bg0Hard',
      syntaxComment: 'gray',
      syntaxKeyword: 'purple',
      syntaxFunction: 'aqua',
      syntaxString: 'green',
      syntaxNumber: 'orange',
      syntaxVariable: 'blue',
      syntaxOperator: 'fg3',
      syntaxPunctuation: 'fg4',
      syntaxType: 'yellow',
    },
  },
  nord: {
    name: 'Nord',
    defs: {
      nord0: '#2e3440',
      nord1: '#3b4252',
      nord2: '#434c5e',
      nord3: '#4c566a',
      nord4: '#d8dee9',
      nord5: '#e5e9f0',
      nord6: '#eceff4',
      nord7: '#8fbcbb',
      nord8: '#88c0d0',
      nord9: '#81a1c1',
      nord10: '#5e81ac',
      nord11: '#bf616a',
      nord12: '#d08770',
      nord13: '#ebcb8b',
      nord14: '#a3be8c',
      nord15: '#b48ead',
      polarNight: '#242933',
    },
    theme: {
      primary: 'nord12',
      secondary: 'nord15',
      accent: 'nord12',
      error: 'nord11',
      warning: 'nord13',
      success: 'nord14',
      info: 'nord8',
      text: 'nord6',
      textMuted: 'nord3',
      background: 'polarNight',
      backgroundPanel: 'nord0',
      backgroundElement: 'nord1',
      backgroundInput: 'nord1',
      backgroundUser: 'nord0',
      backgroundAssistant: 'polarNight',
      border: 'nord2',
      borderActive: 'nord3',
      borderSubtle: 'nord1',
      selectedListItemText: 'polarNight',
      syntaxComment: 'nord3',
      syntaxKeyword: 'nord15',
      syntaxFunction: 'nord8',
      syntaxString: 'nord14',
      syntaxNumber: 'nord12',
      syntaxVariable: 'nord7',
      syntaxOperator: 'nord9',
      syntaxPunctuation: 'nord4',
      syntaxType: 'nord13',
    },
  },
  dracula: {
    name: 'Dracula',
    defs: {
      bg: '#282a36',
      bgDarker: '#21222c',
      bgDarkest: '#191a21',
      currentLine: '#44475a',
      selection: '#44475a',
      fg: '#f8f8f2',
      comment: '#6272a4',
      cyan: '#8be9fd',
      green: '#50fa7b',
      orange: '#ffb86c',
      pink: '#ff79c6',
      purple: '#bd93f9',
      red: '#ff5555',
      yellow: '#f1fa8c',
    },
    theme: {
      primary: 'orange',
      secondary: 'pink',
      accent: 'orange',
      error: 'red',
      warning: 'yellow',
      success: 'green',
      info: 'cyan',
      text: 'fg',
      textMuted: 'comment',
      background: 'bgDarkest',
      backgroundPanel: 'bgDarker',
      backgroundElement: 'bg',
      backgroundInput: 'currentLine',
      backgroundUser: 'bgDarker',
      backgroundAssistant: 'bgDarkest',
      border: 'currentLine',
      borderActive: 'selection',
      borderSubtle: 'bgDarker',
      selectedListItemText: 'bgDarkest',
      syntaxComment: 'comment',
      syntaxKeyword: 'pink',
      syntaxFunction: 'green',
      syntaxString: 'yellow',
      syntaxNumber: 'purple',
      syntaxVariable: 'fg',
      syntaxOperator: 'pink',
      syntaxPunctuation: 'fg',
      syntaxType: 'cyan',
    },
  },
  rosepine: {
    name: 'Rose Pine',
    defs: {
      base: '#191724',
      surface: '#1f1d2e',
      overlay: '#26233a',
      muted: '#6e6a86',
      subtle: '#908caa',
      text: '#e0def4',
      love: '#eb6f92',
      gold: '#f6c177',
      rose: '#ebbcba',
      pine: '#31748f',
      foam: '#9ccfd8',
      iris: '#c4a7e7',
      highlightLow: '#21202e',
      highlightMed: '#403d52',
      highlightHigh: '#524f67',
    },
    theme: {
      primary: 'rose',
      secondary: 'iris',
      accent: 'gold',
      error: 'love',
      warning: 'gold',
      success: 'foam',
      info: 'pine',
      text: 'text',
      textMuted: 'muted',
      background: 'base',
      backgroundPanel: 'surface',
      backgroundElement: 'overlay',
      backgroundInput: 'overlay',
      backgroundUser: 'surface',
      backgroundAssistant: 'base',
      border: 'highlightMed',
      borderActive: 'highlightHigh',
      borderSubtle: 'highlightLow',
      selectedListItemText: 'base',
      syntaxComment: 'muted',
      syntaxKeyword: 'iris',
      syntaxFunction: 'rose',
      syntaxString: 'gold',
      syntaxNumber: 'gold',
      syntaxVariable: 'foam',
      syntaxOperator: 'subtle',
      syntaxPunctuation: 'muted',
      syntaxType: 'love',
    },
  },
  matrix: {
    name: 'Matrix',
    defs: {
      black: '#0d0208',
      darkGreen: '#003b00',
      green1: '#008f11',
      green2: '#00ff41',
      brightGreen: '#39ff14',
      dimGreen: '#00661a',
      gray: '#404040',
      darkGray: '#1a1a1a',
    },
    theme: {
      primary: 'green2',
      secondary: 'green1',
      accent: 'brightGreen',
      error: 'green2',
      warning: 'green2',
      success: 'brightGreen',
      info: 'green1',
      text: 'green2',
      textMuted: 'dimGreen',
      background: 'black',
      backgroundPanel: 'darkGray',
      backgroundElement: 'darkGreen',
      backgroundInput: 'darkGreen',
      backgroundUser: 'darkGray',
      backgroundAssistant: 'black',
      border: 'darkGreen',
      borderActive: 'green1',
      borderSubtle: 'darkGreen',
      selectedListItemText: 'black',
      syntaxComment: 'dimGreen',
      syntaxKeyword: 'brightGreen',
      syntaxFunction: 'green2',
      syntaxString: 'green1',
      syntaxNumber: 'brightGreen',
      syntaxVariable: 'green2',
      syntaxOperator: 'green1',
      syntaxPunctuation: 'dimGreen',
      syntaxType: 'brightGreen',
    },
  },
}

function resolveColor(
  color: ThemeColor,
  defs: ThemeDefs,
  themeObj: ThemeConfig['theme'],
  mode: 'dark' | 'light' = 'dark'
): string {
  // Handle object with dark/light
  if (typeof color === 'object') {
    color = color[mode]
  }

  // Check if it's a reference to defs
  if (defs[color]) {
    return defs[color]
  }

  // Check if it's a reference to another theme property
  const themeKey = color as keyof ThemeConfig['theme']
  if (themeObj[themeKey] && themeKey !== color) {
    return resolveColor(themeObj[themeKey]!, defs, themeObj, mode)
  }

  // Return as-is (should be a hex color)
  return color
}

export function resolveTheme(
  config: ThemeConfig,
  mode: 'dark' | 'light' = 'dark'
): ResolvedTheme {
  const defs = config.defs || {}
  const t = config.theme

  const resolve = (key: keyof ThemeConfig['theme'], fallback?: string): string => {
    const val = t[key]
    if (val === undefined) {
      return fallback || '#ffffff'
    }
    return resolveColor(val, defs, t, mode)
  }

  return {
    name: config.name || 'Custom',
    primary: resolve('primary'),
    secondary: resolve('secondary'),
    accent: resolve('accent'),
    error: resolve('error'),
    warning: resolve('warning'),
    success: resolve('success'),
    info: resolve('info'),
    text: resolve('text'),
    textMuted: resolve('textMuted'),
    background: resolve('background'),
    backgroundPanel: resolve('backgroundPanel'),
    backgroundElement: resolve('backgroundElement'),
    backgroundInput: resolve('backgroundInput', resolve('backgroundElement')),
    backgroundUser: resolve('backgroundUser', resolve('backgroundElement')),
    backgroundAssistant: resolve('backgroundAssistant', resolve('background')),
    border: resolve('border'),
    borderActive: resolve('borderActive'),
    borderSubtle: resolve('borderSubtle', resolve('border')),
    selectedListItemText: resolve('selectedListItemText', resolve('background')),
    syntaxComment: resolve('syntaxComment', resolve('textMuted')),
    syntaxKeyword: resolve('syntaxKeyword', resolve('secondary')),
    syntaxFunction: resolve('syntaxFunction', resolve('primary')),
    syntaxString: resolve('syntaxString', resolve('success')),
    syntaxNumber: resolve('syntaxNumber', resolve('accent')),
    syntaxVariable: resolve('syntaxVariable', resolve('info')),
    syntaxOperator: resolve('syntaxOperator', resolve('secondary')),
    syntaxPunctuation: resolve('syntaxPunctuation', resolve('textMuted')),
    syntaxType: resolve('syntaxType', resolve('warning')),
  }
}

export function getTheme(name: string): ResolvedTheme {
  const config = themes[name] || themes.opencode
  return resolveTheme(config)
}

export function getAvailableThemes(): string[] {
  return Object.keys(themes)
}

export type { ThemeConfig, ResolvedTheme }
